// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package dao

import (
	"context"
	"fmt"
	"testing"

	"github.com/czh0526/kms/store/db/model"
	"gorm.io/gen"
	"gorm.io/gen/field"
	"gorm.io/gorm/clause"
)

func init() {
	InitializeDB()
	err := _gen_test_db.AutoMigrate(&model.KeyPair{})
	if err != nil {
		fmt.Printf("Error: AutoMigrate(&model.KeyPair{}) fail: %s", err)
	}
}

func Test_keyPairQuery(t *testing.T) {
	keyPair := newKeyPair(_gen_test_db)
	keyPair = *keyPair.As(keyPair.TableName())
	_do := keyPair.WithContext(context.Background()).Debug()

	primaryKey := field.NewString(keyPair.TableName(), clause.PrimaryKey)
	_, err := _do.Unscoped().Where(primaryKey.IsNotNull()).Delete()
	if err != nil {
		t.Error("clean table <key_pairs> fail:", err)
		return
	}

	_, ok := keyPair.GetFieldByName("")
	if ok {
		t.Error("GetFieldByName(\"\") from keyPair success")
	}

	err = _do.Create(&model.KeyPair{})
	if err != nil {
		t.Error("create item in table <key_pairs> fail:", err)
	}

	err = _do.Save(&model.KeyPair{})
	if err != nil {
		t.Error("create item in table <key_pairs> fail:", err)
	}

	err = _do.CreateInBatches([]*model.KeyPair{{}, {}}, 10)
	if err != nil {
		t.Error("create item in table <key_pairs> fail:", err)
	}

	_, err = _do.Select(keyPair.ALL).Take()
	if err != nil {
		t.Error("Take() on table <key_pairs> fail:", err)
	}

	_, err = _do.First()
	if err != nil {
		t.Error("First() on table <key_pairs> fail:", err)
	}

	_, err = _do.Last()
	if err != nil {
		t.Error("First() on table <key_pairs> fail:", err)
	}

	_, err = _do.Where(primaryKey.IsNotNull()).FindInBatch(10, func(tx gen.Dao, batch int) error { return nil })
	if err != nil {
		t.Error("FindInBatch() on table <key_pairs> fail:", err)
	}

	err = _do.Where(primaryKey.IsNotNull()).FindInBatches(&[]*model.KeyPair{}, 10, func(tx gen.Dao, batch int) error { return nil })
	if err != nil {
		t.Error("FindInBatches() on table <key_pairs> fail:", err)
	}

	_, err = _do.Select(keyPair.ALL).Where(primaryKey.IsNotNull()).Order(primaryKey.Desc()).Find()
	if err != nil {
		t.Error("Find() on table <key_pairs> fail:", err)
	}

	_, err = _do.Distinct(primaryKey).Take()
	if err != nil {
		t.Error("select Distinct() on table <key_pairs> fail:", err)
	}

	_, err = _do.Select(keyPair.ALL).Omit(primaryKey).Take()
	if err != nil {
		t.Error("Omit() on table <key_pairs> fail:", err)
	}

	_, err = _do.Group(primaryKey).Find()
	if err != nil {
		t.Error("Group() on table <key_pairs> fail:", err)
	}

	_, err = _do.Scopes(func(dao gen.Dao) gen.Dao { return dao.Where(primaryKey.IsNotNull()) }).Find()
	if err != nil {
		t.Error("Scopes() on table <key_pairs> fail:", err)
	}

	_, _, err = _do.FindByPage(0, 1)
	if err != nil {
		t.Error("FindByPage() on table <key_pairs> fail:", err)
	}

	_, err = _do.ScanByPage(&model.KeyPair{}, 0, 1)
	if err != nil {
		t.Error("ScanByPage() on table <key_pairs> fail:", err)
	}

	_, err = _do.Attrs(primaryKey).Assign(primaryKey).FirstOrInit()
	if err != nil {
		t.Error("FirstOrInit() on table <key_pairs> fail:", err)
	}

	_, err = _do.Attrs(primaryKey).Assign(primaryKey).FirstOrCreate()
	if err != nil {
		t.Error("FirstOrCreate() on table <key_pairs> fail:", err)
	}

	var _a _another
	var _aPK = field.NewString(_a.TableName(), "id")

	err = _do.Join(&_a, primaryKey.EqCol(_aPK)).Scan(map[string]interface{}{})
	if err != nil {
		t.Error("Join() on table <key_pairs> fail:", err)
	}

	err = _do.LeftJoin(&_a, primaryKey.EqCol(_aPK)).Scan(map[string]interface{}{})
	if err != nil {
		t.Error("LeftJoin() on table <key_pairs> fail:", err)
	}

	_, err = _do.Not().Or().Clauses().Take()
	if err != nil {
		t.Error("Not/Or/Clauses on table <key_pairs> fail:", err)
	}
}
