// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameKeyPair = "key_pairs"

// KeyPair mapped from table <key_pairs>
type KeyPair struct {
	Address    string `gorm:"column:address" json:"address"`
	PrivateKey string `gorm:"column:private_key" json:"private_key"`
	PublicKey  string `gorm:"column:public_key" json:"public_key"`
}

// TableName KeyPair's table name
func (*KeyPair) TableName() string {
	return TableNameKeyPair
}
